# Generated by Django 4.2 on 2023-04-18 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="storage",
            name="contact",
            field=models.TextField(blank=True, verbose_name="Контакты склада"),
        ),
        migrations.AddField(
            model_name="storage",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание склада"),
        ),
        migrations.AddField(
            model_name="storage",
            name="route_description",
            field=models.TextField(blank=True, verbose_name="Проезд до склада"),
        ),
        migrations.AddField(
            model_name="storage",
            name="special_property",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NEAR_THE_SUBWAY", "Рядом с метро"),
                    ("PARKING", "Парковка"),
                    ("HIGH_CEILING", "Высокие потолки"),
                ],
                max_length=25,
                verbose_name="Свойство склада",
            ),
        ),
        migrations.AddField(
            model_name="storage",
            name="temperature",
            field=models.SmallIntegerField(
                blank=True, null=True, verbose_name="Температура на складе"
            ),
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="imgs/", verbose_name="Изображение"),
                ),
                (
                    "storage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="storage.storage",
                        verbose_name="Склад",
                    ),
                ),
            ],
        ),
    ]
