# Generated by Django 4.2 on 2023-04-18 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0002_storage_contact_storage_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={
                "verbose_name": "Изображение",
                "verbose_name_plural": "Изображения",
            },
        ),
    ]
