# Generated by Django 4.2 on 2023-04-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0003_alter_image_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="box",
            name="floor",
            field=models.SmallIntegerField(blank=True, null=True, verbose_name="Этаж"),
        ),
        migrations.AddField(
            model_name="storage",
            name="max_height",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Максимальная высота потолка",
            ),
            preserve_default=False,
        ),
    ]
