# Generated by Django 4.2 on 2023-04-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0005_alter_order_need_delivery_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Айди платежа"
            ),
        ),
    ]
