version: '3.3'
services:
  backend:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: self-storage-backend
    restart: always
    volumes:
      - media_value:/app/media/
      - static_value:/app/static/
    env_file:
      - ../.env
    depends_on:
      - db
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"

  db:
    image: postgres:13.0-alpine
    volumes:
      - db_value:/var/lib/postgresql/data
    env_file:
      - ../.env
    ports:
      - "5435:5432"

volumes:
  static_value:
  media_value:
  db_value:
